import streamlit as st
import torch
import numpy as np
import plotly.graph_objects as go
from PIL import Image
import time
import sys
import os
import io

# Fix the path issue
# This assumes your script is in a subdirectory, e.g., 'app/main.py'
# and the 'scripts' and 'models' folders are in the parent directory.
try:
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(current_dir, '..'))
    if project_root not in sys.path:
        sys.path.append(project_root)
except NameError:
    # file is not defined in some environments (e.g., interactive notebooks)
    # Fallback for broader compatibility
    project_root = os.path.abspath('.')
    if project_root not in sys.path:
        sys.path.append(project_root)


# Set page config first
st.set_page_config(
    page_title="3D Face Reconstruction",
    page_icon="👤",
    layout="wide"
)

def export_to_obj(vertices, faces, vertex_colors=None, filename="face_reconstruction.obj"):
    """Export mesh data to OBJ format with optional vertex colors as comments."""
    obj_content = []
    
    # Add header
    obj_content.append(f"# 3D Face Reconstruction Export")
    obj_content.append(f"# Vertices: {len(vertices)}, Faces: {len(faces)}")
    obj_content.append(f"# Generated by 3D Face Reconstruction App")
    obj_content.append("")
    
    # Add vertices
    if vertex_colors is not None and len(vertex_colors) == len(vertices):
        # Include vertex colors as comments
        for i, (v, color) in enumerate(zip(vertices, vertex_colors)):
            obj_content.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f} # color({color[0]},{color[1]},{color[2]})")
    else:
        # Just vertices without color info
        for v in vertices:
            obj_content.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    
    obj_content.append("")
    
    # Add faces (OBJ uses 1-based indexing)
    for face in faces:
        # Add 1 to each index for OBJ format
        face_line = "f " + " ".join([str(idx + 1) for idx in face])
        obj_content.append(face_line)
    
    obj_content.append("")
    obj_content.append("# End of file")
    
    return "\n".join(obj_content)

def export_to_obj_with_mtl(vertices, faces, vertex_colors=None, filename="face_reconstruction.obj"):
    """Export mesh data to OBJ format with MTL file for vertex colors."""
    if vertex_colors is None or len(vertex_colors) != len(vertices):
        return export_to_obj(vertices, faces, None, filename)
    
    # Create MTL content
    mtl_content = []
    mtl_content.append("# Material file for 3D Face Reconstruction")
    mtl_content.append("newmtl FaceMaterial")
    mtl_content.append("Ka 1.000 1.000 1.000")  # Ambient
    mtl_content.append("Kd 1.000 1.000 1.000")  # Diffuse
    mtl_content.append("Ks 0.000 0.000 0.000")  # Specular
    mtl_content.append("")
    
    # Create OBJ content
    obj_content = []
    obj_content.append(f"# 3D Face Reconstruction Export with Colors")
    obj_content.append(f"# Vertices: {len(vertices)}, Faces: {len(faces)}")
    obj_content.append(f"mtllib {filename.replace('.obj', '.mtl')}")
    obj_content.append("usemtl FaceMaterial")
    obj_content.append("")
    
    # Add vertices
    for v in vertices:
        obj_content.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    
    obj_content.append("")
    
    # Add vertex colors as vertex normals (workaround for color in some viewers)
    for color in vertex_colors:
        # Normalize colors to [0,1] range
        r, g, b = color[0]/255.0, color[1]/255.0, color[2]/255.0
        obj_content.append(f"vn {r:.6f} {g:.6f} {b:.6f}")
    
    obj_content.append("")
    
    # Add faces with vertex normals
    for face in faces:
        face_line = "f " + " ".join([f"{idx+1}//{idx+1}" for idx in face])
        obj_content.append(face_line)
    
    obj_content.append("")
    obj_content.append("# End of file")
    
    return "\n".join(obj_content), "\n".join(mtl_content)

def main():
    st.title("🎭 3D Face Reconstruction")
    st.markdown("Upload a face image to generate a 3D reconstruction using our trained AI model.")

    # Sidebar with simple controls
    with st.sidebar:
        st.header("⚙ Controls")

        # File upload
        uploaded_file = st.file_uploader(
            "Choose a face image",
            type=['jpg', 'jpeg', 'png'],
            help="Upload a clear frontal face photo"
        )

        st.markdown("---")

        # Display options
        st.subheader("Display Options")
        mesh_style = st.radio(
            "Mesh Style:",
            ["Realistic", "Textured", "Surface", "Wireframe", "Point Cloud"],
            index=0
        )

        show_colors = st.checkbox("Show Colors", False)
        show_axes = st.checkbox("Show Axes", False)

        # Performance options
        st.subheader("Performance")
        simplify_mesh = st.checkbox("Simplify Mesh for Display", True)
        
        st.markdown("---")
        
        # Export options
        st.subheader("📤 Export Options")
        export_format = st.radio(
            "Export Format:",
            ["OBJ (Standard)", "OBJ with Colors"],
            help="Choose the format for exporting the 3D model"
        )

    # Main content area
    col1, col2 = st.columns(2)

    # Initialize session state for storing reconstruction results
    if 'reconstruction_result' not in st.session_state:
        st.session_state.reconstruction_result = None
    if 'mesh_data' not in st.session_state:
        st.session_state.mesh_data = None

    if uploaded_file is not None:
        try:
            # Display original image
            with col1:
                st.subheader("📷 Original Image")
                image = Image.open(uploaded_file)
                st.image(image, caption=f"Original Image: {uploaded_file.name}", use_container_width=True)

                # Image info
                st.write("Image Details:")
                st.write(f"Size: {image.size}")
                st.write(f"Mode: {image.mode}")

            # Reconstruction section
            with col2:
                st.subheader("🔄 3D Reconstruction")

                # Check if we need to run reconstruction or use cached result
                if (st.session_state.reconstruction_result is None or 
                    st.session_state.get('last_uploaded_file') != uploaded_file.name):
                    
                    with st.spinner("Running AI model for 3D face reconstruction..."):
                        try:
                            # Import your inference code
                            from scripts.infer import FaceReconstructor

                            # Initialize reconstructor
                            reconstructor = FaceReconstructor("models/checkpoints/latest.pth")

                            # Perform reconstruction
                            result = reconstructor.reconstruct(image)

                            vertices = result['vertices']
                            faces = result['faces']
                            vertex_colors = result['vertex_colors']

                            # Store in session state
                            st.session_state.reconstruction_result = {
                                'vertices': vertices,
                                'faces': faces,
                                'vertex_colors': vertex_colors
                            }
                            st.session_state.last_uploaded_file = uploaded_file.name
                            st.session_state.mesh_data = None  # Reset mesh data

                            st.success("✅ AI reconstruction complete!")

                        except Exception as e:
                            st.error(f"❌ Model inference failed: {e}")
                            st.info("Using demo face mesh instead...")
                            vertices, faces, vertex_colors = create_demo_face_mesh()
                            
                            # Store demo mesh in session state
                            st.session_state.reconstruction_result = {
                                'vertices': vertices,
                                'faces': faces,
                                'vertex_colors': vertex_colors
                            }
                            st.session_state.last_uploaded_file = uploaded_file.name
                            st.session_state.mesh_data = None
                else:
                    # Use cached result
                    st.info("✅ Using cached reconstruction result")
                    vertices = st.session_state.reconstruction_result['vertices']
                    faces = st.session_state.reconstruction_result['faces']
                    vertex_colors = st.session_state.reconstruction_result['vertex_colors']

                # Display mesh info
                st.write(f"Mesh Info:")
                st.write(f"Vertices: {len(vertices):,}")
                st.write(f"Faces: {len(faces):,}")

                # --- Smarter simplification logic ---
                display_vertices, display_faces, display_colors = vertices, faces, vertex_colors
                
                if mesh_style == "Point Cloud" and simplify_mesh and len(vertices) > 5000:
                    st.info(f"📊 Simplifying point cloud to 5,000 vertices for performance...")
                    display_vertices, display_colors = simplify_point_cloud_data(vertices, vertex_colors, target_vertices=5000)
                    display_faces = None
                
                # Create 3D visualization
                fig = create_3d_visualization(
                    display_vertices, 
                    display_faces, 
                    display_colors, 
                    mesh_style, 
                    show_colors
                )

                if fig is not None:
                    # Update layout
                    fig.update_layout(
                        title="3D Face Reconstruction",
                        scene=dict(
                            aspectratio=dict(x=1, y=1, z=1),
                            camera=dict(
                                eye=dict(x=0, y=0, z=2.5)
                            ),
                        ),
                        margin=dict(l=0, r=0, b=0, t=40)
                    )

                    if show_axes:
                         fig.update_layout(scene=dict(
                            xaxis_title="X", yaxis_title="Y", zaxis_title="Z",
                            xaxis=dict(visible=True, showticklabels=True),
                            yaxis=dict(visible=True, showticklabels=True),
                            zaxis=dict(visible=True, showticklabels=True),
                         ))

                    # Display the plot
                    st.plotly_chart(fig, use_container_width=True)
                    
                    # --- Export Section ---
                    st.markdown("---")
                    st.subheader("📤 Export 3D Model")
                    
                    # Generate export filename
                    base_name = os.path.splitext(uploaded_file.name)[0]
                    obj_filename = f"{base_name}_3d_reconstruction.obj"
                    
                    # Export buttons
                    col_export1, col_export2 = st.columns(2)
                    
                    with col_export1:
                        if export_format == "OBJ (Standard)":
                            obj_content = export_to_obj(vertices, faces, vertex_colors, obj_filename)
                            st.download_button(
                                label="📥 Download OBJ File",
                                data=obj_content,
                                file_name=obj_filename,
                                mime="text/plain",
                                help="Download the 3D model in OBJ format"
                            )
                        else:
                            obj_content, mtl_content = export_to_obj_with_mtl(vertices, faces, vertex_colors, obj_filename)
                            st.download_button(
                                label="📥 Download OBJ+MTL Files",
                                data=obj_content,
                                file_name=obj_filename,
                                mime="text/plain",
                                help="Download OBJ file (MTL will be included as comments)"
                            )
                    
                    with col_export2:
                        # Show export info
                        st.info(f"**Export Info:**\n- Format: {export_format}\n- Vertices: {len(vertices):,}\n- Faces: {len(faces):,}")
                    
                    # Additional export options
                    with st.expander("Advanced Export Options"):
                        st.write("**Export Notes:**")
                        st.write("- OBJ files can be imported into Blender, Maya, 3DS Max, Unity, etc.")
                        st.write("- Vertex colors are preserved in the export")
                        st.write("- For best results, use software that supports vertex colors")
                        
                        # Preview OBJ content
                        if st.checkbox("Preview OBJ file content"):
                            if export_format == "OBJ (Standard)":
                                obj_content_preview = export_to_obj(vertices, faces, vertex_colors, obj_filename)
                            else:
                                obj_content_preview, _ = export_to_obj_with_mtl(vertices, faces, vertex_colors, obj_filename)
                            
                            st.text_area("OBJ File Preview", obj_content_preview, height=200)
                
                else:
                    st.error("❌ Could not create 3D visualization.")

        except Exception as e:
            st.error(f"An error occurred during processing: {str(e)}")
            st.info("Please try with a different image.")

    else:
        # Welcome screen when no image is uploaded
        show_welcome_screen()

def simplify_point_cloud_data(vertices, vertex_colors, target_vertices=5000):
    """Simplifies vertex data for a point cloud display by random sampling."""
    if len(vertices) <= target_vertices:
        return vertices, vertex_colors
    sample_indices = np.random.choice(len(vertices), target_vertices, replace=False)
    vertices_simple = vertices[sample_indices]
    if vertex_colors is not None and len(vertex_colors) == len(vertices):
        vertex_colors_simple = vertex_colors[sample_indices]
    else:
        vertex_colors_simple = None
    return vertices_simple, vertex_colors_simple

def create_3d_visualization(vertices, faces, vertex_colors, mesh_style, show_colors):
    """Create 3D visualization based on the selected style."""
    try:
        if mesh_style == "Realistic":
            return create_realistic_mesh(vertices, faces, vertex_colors, show_colors)
        elif mesh_style == "Point Cloud":
            return create_point_cloud(vertices, vertex_colors, show_colors)
        elif mesh_style == "Wireframe":
            return create_wireframe(vertices, faces)
        elif mesh_style == "Surface":
            return create_surface_mesh(vertices, faces, vertex_colors if show_colors else None)
        elif mesh_style == "Textured":
            return create_textured_mesh(vertices, faces, vertex_colors if show_colors else None)
        else:
            return create_point_cloud(vertices, vertex_colors, show_colors)
    except Exception as e:
        st.error(f"Visualization error in {mesh_style} mode: {e}")
        return create_point_cloud(vertices, vertex_colors, show_colors)

def create_realistic_mesh(vertices, faces, vertex_colors=None, show_colors=True):
    """Create a mesh with a realistic lighting model."""
    mesh_props = {
        'x': vertices[:, 0], 'y': vertices[:, 1], 'z': vertices[:, 2],
        'i': faces[:, 0], 'j': faces[:, 1], 'k': faces[:, 2],
        'opacity': 1.0,
        'flatshading': False,
        'lighting': {
            'ambient': 0.4,
            'diffuse': 1.0,
            'specular': 0.5,
            'roughness': 0.5,
            'fresnel': 0.2
        },
        'lightposition': {'x': 100, 'y': 200, 'z': 0}
    }

    if vertex_colors is not None and show_colors:
        mesh_props['vertexcolor'] = [f'rgb({c[0]},{c[1]},{c[2]})' for c in vertex_colors]
    else:
        # A neutral skin-like tone as a fallback
        mesh_props['color'] = 'rgb(224,172,144)'

    fig = go.Figure(data=[go.Mesh3d(**mesh_props)])
    
    fig.update_layout(scene=dict(
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
        zaxis=dict(visible=False)
    ))
    return fig

def create_point_cloud(vertices, vertex_colors, show_colors):
    """Create point cloud visualization."""
    marker_props = dict(size=2, opacity=0.8)
    if show_colors and vertex_colors is not None and len(vertex_colors) == len(vertices):
        marker_props['color'] = vertex_colors
    else:
        marker_props['color'] = 'lightblue'
    fig = go.Figure(data=[go.Scatter3d(
        x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
        mode='markers', marker=marker_props, name='Face Points'
    )])
    return fig

def create_wireframe(vertices, faces):
    """Create an efficient wireframe visualization."""
    x_coords, y_coords, z_coords = [], [], []
    for face in faces:
        for i in range(3):
            v_start_idx, v_end_idx = face[i], face[(i + 1) % 3]
            x_coords.extend([vertices[v_start_idx][0], vertices[v_end_idx][0], None])
            y_coords.extend([vertices[v_start_idx][1], vertices[v_end_idx][1], None])
            z_coords.extend([vertices[v_start_idx][2], vertices[v_end_idx][2], None])
    fig = go.Figure(data=[go.Scatter3d(
        x=x_coords, y=y_coords, z=z_coords,
        mode='lines', line=dict(color='deepskyblue', width=1), name='Wireframe'
    )])
    return fig

def create_surface_mesh(vertices, faces, vertex_colors=None):
    """Create a solid surface mesh visualization."""
    mesh_props = {
        'x': vertices[:, 0], 'y': vertices[:, 1], 'z': vertices[:, 2],
        'i': faces[:, 0], 'j': faces[:, 1], 'k': faces[:, 2],
        'opacity': 0.9, 'flatshading': True
    }
    if vertex_colors is not None:
        mesh_props['vertexcolor'] = [f'rgb({c[0]},{c[1]},{c[2]})' for c in vertex_colors]
    else:
        mesh_props['color'] = 'lightpink'
    fig = go.Figure(data=[go.Mesh3d(**mesh_props)])
    return fig

def create_textured_mesh(vertices, faces, vertex_colors=None):
    """Create a textured mesh (identical to surface mesh with vertex colors)."""
    return create_surface_mesh(vertices, faces, vertex_colors)

def create_demo_face_mesh():
    """Create a simple demo face mesh for display when the model fails."""
    phi = np.linspace(0, np.pi, 30)
    theta = np.linspace(0, 2 * np.pi, 40)
    phi, theta = np.meshgrid(phi, theta)
    x = np.sin(phi) * np.cos(theta)
    y = np.sin(phi) * np.sin(theta) * 1.2
    z = np.cos(phi)
    nose_mask = (np.abs(y) < 0.2) & (x > 0.8)
    x[nose_mask] = x[nose_mask] * 1.15
    vertices = np.vstack([x.ravel(), y.ravel(), z.ravel()]).T
    faces = []
    rows, cols = phi.shape
    for r in range(rows - 1):
        for c in range(cols - 1):
            v1, v2, v3, v4 = r*cols+c, r*cols+(c+1), (r+1)*cols+c, (r+1)*cols+(c+1)
            faces.extend([[v1, v2, v4], [v1, v4, v3]])
    base_color = np.array([224, 172, 144])
    color_variation = np.random.randint(-15, 15, size=(len(vertices), 3))
    vertex_colors = np.clip(base_color + color_variation, 0, 255)
    return vertices, np.array(faces), vertex_colors

def show_welcome_screen():
    """Show the initial welcome screen with instructions and a demo."""
    st.info("👋 Welcome! Please upload a face image using the controls in the sidebar to get started.")
    st.markdown("---")
    col1, col2 = st.columns([2, 1])
    with col1:
        st.subheader("🚀 How It Works")
        st.markdown("1.  Upload a clear, front-facing photo.\n"
                    "2.  Our AI model analyzes the image to predict its 3D shape and texture.\n"
                    "3.  Explore the 3D mesh result.\n"
                    "4.  Use the Display Options to change the style.\n"
                    "5.  **NEW**: Export your 3D model as OBJ file!")
    with col2:
        st.subheader("✨ Display Modes")
        st.markdown("-   Realistic: The most lifelike view with lighting and shadows.\n"
                    "-   Textured: A solid surface with colors from the image.\n"
                    "-   Surface: A solid surface with a default color.\n"
                    "-   Wireframe: Shows the underlying geometric structure.\n"
                    "-   Point Cloud: Displays only the 3D points.")
    
    st.markdown("---")
    st.subheader("📤 New Export Feature")
    st.markdown("""
    **Export your 3D reconstructions as OBJ files!**
    - Compatible with Blender, Maya, Unity, and other 3D software
    - Preserves vertex colors and geometry
    - Choose between standard OBJ or color-enhanced formats
    - Perfect for 3D printing, animation, or further editing
    """)

if __name__ == "__main__":
    main()